#%RAML 1.0 DataType
type: object
properties:
  email: string
  address: string
  contactInfo: string
  birthdate: string
  accountType?: 
    enum: [personal, banker]
  firstName: string
  lastName: string
  nationality?: string
  username: string
  password: string